# This Makefile was generated by the made script:
# https://github.com/alx741/made
#
# Dependencies:
# 	pandoc
# 	pandoc-citeproc

INPUTS = $(shell find . -type f -name '*.md')
OUTPUTS = $(foreach input, $(INPUTS), $(input:.md=.pdf))

all: $(OUTPUTS)

%.pdf: %.md
	pandoc -V geometry:margin=1in $< -o $@

clean:
	rm $(OUTPUTS)
